Controllers films users
den4ikos/java-filmorate pull request #1
Opened 2022-09-21 17:36 UTC by den4ikos

2022-09-22 19:58 UTC, krylov-sergey-sergeevich requested changes
1) Не нашёл тесты 
2) Ну и мелкие заметки оставил

2022-09-22 19:58 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    List<Film> films = new ArrayList<>();
Модификаторы доступа давай добавим:)

2022-09-22 19:58 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +
Статик?)

2022-09-22 19:58 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        final List<Film> filmList = films.stream().filter(f -> Objects.equals(f.getId(), film.getId())).collect(Collectors.toList());
А зачем внутри метода модификаторы доступа?

2022-09-22 19:58 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private static Long id = 0L;
Статик

2022-09-22 19:58 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        final List<User> userById = users.stream().filter(u -> Objects.equals(u.getId(), user.getId())).collect(Collectors.toList());
Вроде есть метод что то вроде findBy или findAll()

2022-09-22 19:58 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/validation/DateValidation.java
> +public class DateValidation {
Это класс - узкая утилита, лучше уж тогда использовать его полностью как статичный, сделать статичные методы и переменные

2022-09-22 19:58 UTC, krylov-sergey-sergeevich commented on src/main/resources/application.properties
> +server.port=8080
Если вас учили то попробуй переписать конфиг на yaml формат

2022-09-23 11:00 UTC, den4ikos commented on src/main/resources/application.properties
> +server.port=8080
Такого еще не проходили

2022-09-24 09:41 UTC, den4ikos commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    List<Film> films = new ArrayList<>();
добавил

2022-09-24 09:45 UTC, den4ikos commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        final List<User> userById = users.stream().filter(u -> Objects.equals(u.getId(), user.getId())).collect(Collectors.toList());
Да вроде как нету, или я просто не знаю

2022-09-24 09:46 UTC, den4ikos commented on src/main/java/ru/yandex/practicum/filmorate/validation/DateValidation.java
> +public class DateValidation {
исправил

2022-09-24 09:48 UTC, den4ikos commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private static Long id = 0L;
исправил

2022-09-24 09:49 UTC, den4ikos commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        final List<Film> filmList = films.stream().filter(f -> Objects.equals(f.getId(), film.getId())).collect(Collectors.toList());
исправил

2022-09-24 09:49 UTC, den4ikos commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +
исправил

2022-09-25 17:21 UTC, krylov-sergey-sergeevich approved these changes
В целом хорошо, много небольших помарок, но они думаю спокойно исправятся до следующей работы - поэтому зачет!

2022-09-25 17:21 UTC, krylov-sergey-sergeevich commented on pom.xml
> +	<version>0.0.1-SNAPSHOT</version>
Рекомендую всегда делать осмысленные версии, например 1.0.0

2022-09-25 17:21 UTC, krylov-sergey-sergeevich commented on pom.xml
> +		<dependency>
Рекомендую добавлять комменты в зависимостях и разбивать на логические блоки

2022-09-25 17:21 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private Long id = 0L;
Ну мы понимаем, что когда изучим многопоточность тут надо будет рефакторить код

p.s оставь сам себе todo комментарий

2022-09-25 17:21 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if ( !DateValidation.checkDate(film.getReleaseDate()) ) {
Вижу что эти проверки дублируются, давай вынесем в отдельный метод

2022-09-25 17:21 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private List<User> users = new ArrayList<>();
Оставим комментарий что в будущем надо рефакторить

2022-09-25 17:21 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +    private String message;
Пустую строку давай добавим и наверно можно final добавить

2022-09-25 17:21 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@Data
Пустую строку перед Data

2022-09-25 17:21 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Long id;
Пустую строку после id

2022-09-25 17:21 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Long id;
Пустую строку после id

2022-09-25 17:21 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/validation/DateValidation.java
> +    private static final String DATE_BEFORE = "1895-12-28";
Пустую строку

2022-09-25 17:21 UTC, krylov-sergey-sergeevich commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +    private Film film;
Лучше таким подходом не пользоваться и каждый раз для каждого теста создавать свой объект

2022-09-25 17:21 UTC, krylov-sergey-sergeevich commented on src/test/java/ru/yandex/practicum/filmorate/UserControllerTest.java
> +    private User user;
Лучше в каждом методе создавать

2022-10-02 08:51 UTC, merged