Add friends likes
den4ikos/java-filmorate pull request #2
Opened 2022-10-04 20:39 UTC by den4ikos

2022-10-05 19:57 UTC, krylov-sergey-sergeevich requested changes
Привет, как первое приближение давай сделаем такую лайт проверку - да и код в целом вроде хороший. Но как задача на развитие написать тесты если есть желание + попытаться прикрутить линтер для того чтобы код был всегда красивый (если есть желание). Плюс статья на подумать https://habr.com/ru/post/528116/

2022-10-05 19:57 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private FilmService filmService;
final

2022-10-05 19:57 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService) {
Предлагаю сделать так чтобы конструктора не было, для этого используй ломбок аннотации

2022-10-05 19:57 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public UserController(UserService userService) {
Предлагаю сделать так чтобы конструктора не было, для этого используй ломбок аннотации

2022-10-05 19:57 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private UserService userService;
final

2022-10-05 19:57 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public void setLike(Long userId) {
может addLike?

2022-10-05 19:57 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(InMemoryFilmStorage filmStorage) {
Предлагаю сделать так чтобы конструктора не было, для этого используй ломбок аннотации

2022-10-05 19:57 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private FilmStorage filmStorage;
final

2022-10-05 19:57 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService(InMemoryUserStorage userStorage) {
Предлагаю сделать так чтобы конструктора не было, для этого используй ломбок аннотации

2022-10-05 19:57 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private List<Film> films = new ArrayList<>();
Предлагаю подумать над более эффективной структурой для хранения данных

2022-10-05 19:57 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +
Почему пусто?)

2022-10-05 19:57 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    private List<User> users = new ArrayList<>();
Более эффективную надо структуру

2022-10-05 19:57 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +
Пусто =(

2022-10-06 05:56 UTC, den4ikos commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private FilmService filmService;
+

2022-10-06 05:57 UTC, den4ikos commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService) {
поправил

2022-10-06 05:57 UTC, den4ikos commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public UserController(UserService userService) {
поправил

2022-10-06 05:57 UTC, den4ikos commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private UserService userService;
исправил

2022-10-06 05:59 UTC, den4ikos commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public void setLike(Long userId) {
исправил

2022-10-06 06:00 UTC, den4ikos commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService(InMemoryUserStorage userStorage) {
исправил

2022-10-06 06:17 UTC, den4ikos commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +
В тз ничего не сказано об удалении пользователей и фильмов, и для тестирования в постмане тоже ендпоинта нету. Сказано лишь, что интерфейс должен содержать базовые crud операции. Вот я просто и определил этот метод, но не реализовывал. Сейчас исправил

2022-10-06 06:18 UTC, den4ikos commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +
В тз ничего не сказано об удалении пользователей и фильмов, и для тестирования в постмане тоже ендпоинта нету. Сказано лишь, что интерфейс должен содержать базовые crud операции. Вот я просто и определил этот метод, но не реализовывал. Сейчас исправил

2022-10-06 14:35 UTC, den4ikos commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private List<Film> films = new ArrayList<>();
Исправил

2022-10-06 14:36 UTC, den4ikos commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    private List<User> users = new ArrayList<>();
исправил

2022-10-06 14:45 UTC, den4ikos commented
тесты прикрутил

по поводу линтера - прикрутил checkStyle, но столько варниногов повылазило, по типу не написаны java доки и прочее. Я понимаю, что можно задать како-то конфиг, где можно задизейблить некоторые настройки, но потребуется больше времени, чтобы разобраться. Если есть какие то линтеры, которые принято использовать в сообществе разработчиков вместо checkStyle, то напиши, я почитаю доки. Но в нете вроде как написано, что checkStyle один из популярных.

Статью почитал, вроде как у меня так и было - я через RestControllerAdvice делал, но может я не понял, что ты хотел до меня донести...)

Остальные моменты пофиксил

2022-10-07 15:57 UTC, krylov-sergey-sergeevich approved these changes
Привет, ну достойно - в целом все неплохо выглядит, пару замечаний написал, но по мелочи. На счет checkStyle - это и правда стандарт и рекомендую поизучать и если надо себе некоторые настройки выключить, но в целом использовать.

2022-10-07 15:57 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +public class ErrorHandler {
Хотел как мысль для развития предложить чтобы в ошибке возвращало автоматически url по которому был запрос отправлен

2022-10-07 15:57 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    public void setFriends(Long friendId) {
addFriend

2022-10-07 15:57 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    Map<Long, Film> get();
лучше добавлять пустые строки между методами

2022-10-07 15:57 UTC, krylov-sergey-sergeevich commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +        validFilm = "{\"id\":null,\"name\":\"Film Name\",\"description\":\"Film description\",\"releaseDate\":\"2015-03-01\",\"duration\":100}";
Можно класть json файл рядом и читать его в тесте

2022-10-07 15:57 UTC, krylov-sergey-sergeevich commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    String validFilm;
Лучше не делать подобные переменные общими

2022-10-07 19:37 UTC, merged