Add database
den4ikos/java-filmorate pull request #3
Opened 2022-11-07 09:51 UTC by den4ikos

2022-11-08 06:42 UTC, krylov-sergey-sergeevich requested changes
Привет, в целом неплохо - давай поправим замечания и по тестам их как будто бы немного мало, или я ошибаюсь?

2022-11-08 06:42 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/Constants.java
>  public class Constants {
Интересный подход

2022-11-08 06:42 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +        return mpaService.findById(id);
А что если элемент не будет найден?

2022-11-08 06:42 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
> +    public List<Mpa> get() {
get плохое название, тогда уж getAll

2022-11-08 06:42 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
> +        if (!mpaFromQuery.isEmpty()) {
А почему бы просто не вернуть все значения. если пусто то пусто

2022-11-08 06:42 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +@Qualifier("dbUserStorage")
Эту аннотацию лучше над переменной вешать которую мы хотим получить, а не над классом

2022-11-08 06:42 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +@Component("dbFilmStorage")
А зачем ему такое имя даем? Если у него по умолчанию уже будет вот такое: filmDbStorage

2022-11-08 06:42 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreDbStorage.java
> +@Component("dbGenreStorage")
Опять зачем даем свое имя

2022-11-08 06:42 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreDbStorage.java
> +    public Map<Long, Genre> get() {
getAll

2022-11-08 06:42 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +@Component("inMemoryFilmStorage")
У бина по умолчанию такое имя будет

2022-11-08 06:42 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            public Film getById(Long id) {
Поехал стиль

2022-11-08 06:42 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        user.getFriends().remove(friend.getId());
Лучше у класса User создать метод сразу deleteFriend и внутри него сделать getFriends().remove() чтобы логика удаления была скрыта

2022-11-08 06:42 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreStorage.java
> +    Map<Long, Genre> get();
Плохое название

2022-11-08 06:42 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    List<Film> find(Map<String, String> params);
Плохое название

2022-11-08 06:42 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MpaStorage.java
> +    Map<Long, Mpa> get();
Плохое название

2022-11-08 16:35 UTC, den4ikos commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +        return mpaService.findById(id);
выбросит исключение "notFound": "There is no any MPA!"

2022-11-08 16:37 UTC, den4ikos commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
> +    public List<Mpa> get() {
пофиксил

2022-11-08 16:42 UTC, den4ikos commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
> +        if (!mpaFromQuery.isEmpty()) {
пофиксил

2022-11-08 17:23 UTC, den4ikos commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +@Component("dbFilmStorage")
пофиксил

2022-11-08 17:24 UTC, den4ikos commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreDbStorage.java
> +@Component("dbGenreStorage")
пофиксил - это я скорее в учебных целях эксперементировал, давал разные имена, просто смотрел, как работает

2022-11-08 17:25 UTC, den4ikos commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreDbStorage.java
> +    public Map<Long, Genre> get() {
пофиксил

2022-11-08 17:26 UTC, den4ikos commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +@Component("inMemoryFilmStorage")
пофиксил

2022-11-08 17:27 UTC, den4ikos commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            public Film getById(Long id) {
исправил

2022-11-08 17:52 UTC, den4ikos commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        user.getFriends().remove(friend.getId());
исправил

2022-11-08 17:57 UTC, den4ikos commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreStorage.java
> +    Map<Long, Genre> get();
исправил

2022-11-08 17:59 UTC, den4ikos commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    List<Film> find(Map<String, String> params);
пофиксил

2022-11-08 18:00 UTC, den4ikos commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MpaStorage.java
> +    Map<Long, Mpa> get();
пофиксил

2022-11-08 18:12 UTC, den4ikos commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +@Qualifier("dbUserStorage")
тут у меня варнинг вылазит, Lombok does not copy the annotation into the constructor

2022-11-09 17:27 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет

2022-11-18 20:29 UTC, merged